on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "Source Repository (format: username/repository)"
        required: true
      source_branch:
        description: "Source Branch"
        required: true
      target_repo:
        description: "Target Repository (format: username/repository)"
        required: true
      target_branch:
        description: "Target Branch"
        required: true

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.source_branch }}
          token: ${{ secrets.GH_PAT }}

      - name: Clone Target Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git clone https://$GH_PAT@github.com/${{ github.event.inputs.target_repo }} target-repo

      - name: Copy Files to Target Repository
        run: |
          rsync -av --exclude='.git' --exclude='.github' --exclude='target-repo' ./ target-repo/

      - name: Push to Target Repository
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd target-repo
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Manually synced files from ${{ github.event.inputs.source_repo }} (branch: ${{ github.event.inputs.source_branch }})" || exit 0
          git push origin ${{ github.event.inputs.target_branch }} || {
            echo "Error pushing to target repository"
            exit 1
          }
